name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtirpc-dev
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure --prefix=/usr
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: |
          NAME=unfs3-`arch`-g`git rev-parse --short HEAD`
          mkdir $NAME
          make install DESTDIR=`pwd`/$NAME
          tar -acf $NAME.tar.xz $NAME
      - uses: actions/upload-artifact@v4
        with:
          name: Linux (Ubuntu)
          path: build/unfs3-*.tar.xz

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install autoconf automake libtool
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure --prefix=/usr
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: |
          NAME=unfs3-`arch`-g`git rev-parse --short HEAD`
          mkdir $NAME
          make install DESTDIR=`pwd`/$NAME
          tar -acf $NAME.tar.xz $NAME
      - uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: build/unfs3-*.tar.xz
